// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: api/proto/friend.proto

package friend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FriendService_PendingRequest_FullMethodName        = "/friend.FriendService/PendingRequest"
	FriendService_ConfirmRequest_FullMethodName        = "/friend.FriendService/ConfirmRequest"
	FriendService_GetFriends_FullMethodName            = "/friend.FriendService/GetFriends"
	FriendService_GetPendingRequests_FullMethodName    = "/friend.FriendService/GetPendingRequests"
	FriendService_DeleteFriend_FullMethodName          = "/friend.FriendService/DeleteFriend"
	FriendService_CreateFriendGroup_FullMethodName     = "/friend.FriendService/CreateFriendGroup"
	FriendService_AddFriendToGroup_FullMethodName      = "/friend.FriendService/AddFriendToGroup"
	FriendService_GetFriendGroup_FullMethodName        = "/friend.FriendService/GetFriendGroup"
	FriendService_DeleteFriendFromGroup_FullMethodName = "/friend.FriendService/DeleteFriendFromGroup"
	FriendService_CheckIsFriend_FullMethodName         = "/friend.FriendService/CheckIsFriend"
)

// FriendServiceClient is the client API for FriendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendServiceClient interface {
	PendingRequest(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	ConfirmRequest(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error)
	GetPendingRequests(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error)
	DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	CreateFriendGroup(ctx context.Context, in *CreateFriendGroupRequest, opts ...grpc.CallOption) (*CreateFriendGroupResponse, error)
	AddFriendToGroup(ctx context.Context, in *AddFriendToGroupRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	GetFriendGroup(ctx context.Context, in *GetFriendGroupRequest, opts ...grpc.CallOption) (*GetFriendGroupResponse, error)
	DeleteFriendFromGroup(ctx context.Context, in *AddFriendToGroupRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	CheckIsFriend(ctx context.Context, in *CheckIsFriendRequest, opts ...grpc.CallOption) (*CheckIsFriendResponse, error)
}

type friendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendServiceClient(cc grpc.ClientConnInterface) FriendServiceClient {
	return &friendServiceClient{cc}
}

func (c *friendServiceClient) PendingRequest(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, FriendService_PendingRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ConfirmRequest(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, FriendService_ConfirmRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendsResponse)
	err := c.cc.Invoke(ctx, FriendService_GetFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetPendingRequests(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendsResponse)
	err := c.cc.Invoke(ctx, FriendService_GetPendingRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, FriendService_DeleteFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) CreateFriendGroup(ctx context.Context, in *CreateFriendGroupRequest, opts ...grpc.CallOption) (*CreateFriendGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFriendGroupResponse)
	err := c.cc.Invoke(ctx, FriendService_CreateFriendGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) AddFriendToGroup(ctx context.Context, in *AddFriendToGroupRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, FriendService_AddFriendToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) GetFriendGroup(ctx context.Context, in *GetFriendGroupRequest, opts ...grpc.CallOption) (*GetFriendGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendGroupResponse)
	err := c.cc.Invoke(ctx, FriendService_GetFriendGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) DeleteFriendFromGroup(ctx context.Context, in *AddFriendToGroupRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, FriendService_DeleteFriendFromGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) CheckIsFriend(ctx context.Context, in *CheckIsFriendRequest, opts ...grpc.CallOption) (*CheckIsFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckIsFriendResponse)
	err := c.cc.Invoke(ctx, FriendService_CheckIsFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendServiceServer is the server API for FriendService service.
// All implementations must embed UnimplementedFriendServiceServer
// for forward compatibility.
type FriendServiceServer interface {
	PendingRequest(context.Context, *AddFriendRequest) (*GeneralResponse, error)
	ConfirmRequest(context.Context, *AddFriendRequest) (*GeneralResponse, error)
	GetFriends(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error)
	GetPendingRequests(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error)
	DeleteFriend(context.Context, *DeleteFriendRequest) (*GeneralResponse, error)
	CreateFriendGroup(context.Context, *CreateFriendGroupRequest) (*CreateFriendGroupResponse, error)
	AddFriendToGroup(context.Context, *AddFriendToGroupRequest) (*GeneralResponse, error)
	GetFriendGroup(context.Context, *GetFriendGroupRequest) (*GetFriendGroupResponse, error)
	DeleteFriendFromGroup(context.Context, *AddFriendToGroupRequest) (*GeneralResponse, error)
	CheckIsFriend(context.Context, *CheckIsFriendRequest) (*CheckIsFriendResponse, error)
	mustEmbedUnimplementedFriendServiceServer()
}

// UnimplementedFriendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendServiceServer struct{}

func (UnimplementedFriendServiceServer) PendingRequest(context.Context, *AddFriendRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingRequest not implemented")
}
func (UnimplementedFriendServiceServer) ConfirmRequest(context.Context, *AddFriendRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmRequest not implemented")
}
func (UnimplementedFriendServiceServer) GetFriends(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriends not implemented")
}
func (UnimplementedFriendServiceServer) GetPendingRequests(context.Context, *GetFriendsRequest) (*GetFriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingRequests not implemented")
}
func (UnimplementedFriendServiceServer) DeleteFriend(context.Context, *DeleteFriendRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFriend not implemented")
}
func (UnimplementedFriendServiceServer) CreateFriendGroup(context.Context, *CreateFriendGroupRequest) (*CreateFriendGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFriendGroup not implemented")
}
func (UnimplementedFriendServiceServer) AddFriendToGroup(context.Context, *AddFriendToGroupRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFriendToGroup not implemented")
}
func (UnimplementedFriendServiceServer) GetFriendGroup(context.Context, *GetFriendGroupRequest) (*GetFriendGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriendGroup not implemented")
}
func (UnimplementedFriendServiceServer) DeleteFriendFromGroup(context.Context, *AddFriendToGroupRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFriendFromGroup not implemented")
}
func (UnimplementedFriendServiceServer) CheckIsFriend(context.Context, *CheckIsFriendRequest) (*CheckIsFriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIsFriend not implemented")
}
func (UnimplementedFriendServiceServer) mustEmbedUnimplementedFriendServiceServer() {}
func (UnimplementedFriendServiceServer) testEmbeddedByValue()                       {}

// UnsafeFriendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendServiceServer will
// result in compilation errors.
type UnsafeFriendServiceServer interface {
	mustEmbedUnimplementedFriendServiceServer()
}

func RegisterFriendServiceServer(s grpc.ServiceRegistrar, srv FriendServiceServer) {
	// If the following call pancis, it indicates UnimplementedFriendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FriendService_ServiceDesc, srv)
}

func _FriendService_PendingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).PendingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_PendingRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).PendingRequest(ctx, req.(*AddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ConfirmRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ConfirmRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ConfirmRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ConfirmRequest(ctx, req.(*AddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetFriends(ctx, req.(*GetFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetPendingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetPendingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetPendingRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetPendingRequests(ctx, req.(*GetFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_DeleteFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).DeleteFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_DeleteFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).DeleteFriend(ctx, req.(*DeleteFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_CreateFriendGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFriendGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).CreateFriendGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_CreateFriendGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).CreateFriendGroup(ctx, req.(*CreateFriendGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_AddFriendToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).AddFriendToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_AddFriendToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).AddFriendToGroup(ctx, req.(*AddFriendToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_GetFriendGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).GetFriendGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_GetFriendGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).GetFriendGroup(ctx, req.(*GetFriendGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_DeleteFriendFromGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).DeleteFriendFromGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_DeleteFriendFromGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).DeleteFriendFromGroup(ctx, req.(*AddFriendToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_CheckIsFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIsFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).CheckIsFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_CheckIsFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).CheckIsFriend(ctx, req.(*CheckIsFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FriendService_ServiceDesc is the grpc.ServiceDesc for FriendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friend.FriendService",
	HandlerType: (*FriendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PendingRequest",
			Handler:    _FriendService_PendingRequest_Handler,
		},
		{
			MethodName: "ConfirmRequest",
			Handler:    _FriendService_ConfirmRequest_Handler,
		},
		{
			MethodName: "GetFriends",
			Handler:    _FriendService_GetFriends_Handler,
		},
		{
			MethodName: "GetPendingRequests",
			Handler:    _FriendService_GetPendingRequests_Handler,
		},
		{
			MethodName: "DeleteFriend",
			Handler:    _FriendService_DeleteFriend_Handler,
		},
		{
			MethodName: "CreateFriendGroup",
			Handler:    _FriendService_CreateFriendGroup_Handler,
		},
		{
			MethodName: "AddFriendToGroup",
			Handler:    _FriendService_AddFriendToGroup_Handler,
		},
		{
			MethodName: "GetFriendGroup",
			Handler:    _FriendService_GetFriendGroup_Handler,
		},
		{
			MethodName: "DeleteFriendFromGroup",
			Handler:    _FriendService_DeleteFriendFromGroup_Handler,
		},
		{
			MethodName: "CheckIsFriend",
			Handler:    _FriendService_CheckIsFriend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/friend.proto",
}
