services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: user_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --requirepass 111
    volumes:
      - redis-data:/data

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server --console-address ':9001' /data  
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
    external: true
    name: chat_mysql-data
  redis-data:
    external: true
    name: chat_redis-data
  minio-data:
    external: true
    name: chat_minio-data