// Code generated by goctl. DO NOT EDIT.
// Source: groupMessage.proto

package groupmessageservice

import (
	"context"

	"chatting/service/groupMessageService/pb/groupMessage"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddGroupMemberRequest    = groupMessage.AddGroupMemberRequest
	AddGroupMemberResponse   = groupMessage.AddGroupMemberResponse
	CreateGroupRequest       = groupMessage.CreateGroupRequest
	CreateGroupResponse      = groupMessage.CreateGroupResponse
	GetGroupMessagesRequest  = groupMessage.GetGroupMessagesRequest
	GetGroupMessagesResponse = groupMessage.GetGroupMessagesResponse
	GroupMessage             = groupMessage.GroupMessage
	SendGroupMessageRequest  = groupMessage.SendGroupMessageRequest
	SendGroupMessageResponse = groupMessage.SendGroupMessageResponse

	GroupMessageService interface {
		SendGroupMessage(ctx context.Context, in *SendGroupMessageRequest, opts ...grpc.CallOption) (*SendGroupMessageResponse, error)
		GetGroupMessages(ctx context.Context, in *GetGroupMessagesRequest, opts ...grpc.CallOption) (*GetGroupMessagesResponse, error)
		CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
		AddGroupMember(ctx context.Context, in *AddGroupMemberRequest, opts ...grpc.CallOption) (*AddGroupMemberResponse, error)
	}

	defaultGroupMessageService struct {
		cli zrpc.Client
	}
)

func NewGroupMessageService(cli zrpc.Client) GroupMessageService {
	return &defaultGroupMessageService{
		cli: cli,
	}
}

func (m *defaultGroupMessageService) SendGroupMessage(ctx context.Context, in *SendGroupMessageRequest, opts ...grpc.CallOption) (*SendGroupMessageResponse, error) {
	client := groupMessage.NewGroupMessageServiceClient(m.cli.Conn())
	return client.SendGroupMessage(ctx, in, opts...)
}

func (m *defaultGroupMessageService) GetGroupMessages(ctx context.Context, in *GetGroupMessagesRequest, opts ...grpc.CallOption) (*GetGroupMessagesResponse, error) {
	client := groupMessage.NewGroupMessageServiceClient(m.cli.Conn())
	return client.GetGroupMessages(ctx, in, opts...)
}

func (m *defaultGroupMessageService) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	client := groupMessage.NewGroupMessageServiceClient(m.cli.Conn())
	return client.CreateGroup(ctx, in, opts...)
}

func (m *defaultGroupMessageService) AddGroupMember(ctx context.Context, in *AddGroupMemberRequest, opts ...grpc.CallOption) (*AddGroupMemberResponse, error) {
	client := groupMessage.NewGroupMessageServiceClient(m.cli.Conn())
	return client.AddGroupMember(ctx, in, opts...)
}
