// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"chatting/service/userService/internal/logic"
	"chatting/service/userService/internal/svc"
	"chatting/service/userService/pb/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) Logout(ctx context.Context, in *user.LogoutRequest) (*user.LogoutResponse, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *UserServiceServer) ValidateJWT(ctx context.Context, in *user.ValidateRequest) (*user.ValidateResponse, error) {
	l := logic.NewValidateJWTLogic(ctx, s.svcCtx)
	return l.ValidateJWT(in)
}

func (s *UserServiceServer) UpdateUserProfile(ctx context.Context, in *user.UpdateUserProfileRequest) (*user.UpdateUserProfileResponse, error) {
	l := logic.NewUpdateUserProfileLogic(ctx, s.svcCtx)
	return l.UpdateUserProfile(in)
}

func (s *UserServiceServer) GetUserProfile(ctx context.Context, in *user.GetUserProfileRequest) (*user.GetUserProfileResponse, error) {
	l := logic.NewGetUserProfileLogic(ctx, s.svcCtx)
	return l.GetUserProfile(in)
}

func (s *UserServiceServer) CheckUserExist(ctx context.Context, in *user.CheckUserExistRequest) (*user.CheckUserExistResponse, error) {
	l := logic.NewCheckUserExistLogic(ctx, s.svcCtx)
	return l.CheckUserExist(in)
}

func (s *UserServiceServer) GetUserNameById(ctx context.Context, in *user.GetUserNameByIdRequest) (*user.GetUserNameByIdResponse, error) {
	l := logic.NewGetUserNameByIdLogic(ctx, s.svcCtx)
	return l.GetUserNameById(in)
}
