// Code generated by goctl. DO NOT EDIT.
// Source: friend.proto

package server

import (
	"context"

	"chatting/service/friendService/internal/logic"
	"chatting/service/friendService/internal/svc"
	"chatting/service/friendService/pb/friend"
)

type FriendServiceServer struct {
	svcCtx *svc.ServiceContext
	friend.UnimplementedFriendServiceServer
}

func NewFriendServiceServer(svcCtx *svc.ServiceContext) *FriendServiceServer {
	return &FriendServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendServiceServer) PendingRequest(ctx context.Context, in *friend.AddFriendRequest) (*friend.GeneralResponse, error) {
	l := logic.NewPendingRequestLogic(ctx, s.svcCtx)
	return l.PendingRequest(in)
}

func (s *FriendServiceServer) ConfirmRequest(ctx context.Context, in *friend.AddFriendRequest) (*friend.GeneralResponse, error) {
	l := logic.NewConfirmRequestLogic(ctx, s.svcCtx)
	return l.ConfirmRequest(in)
}

func (s *FriendServiceServer) GetFriends(ctx context.Context, in *friend.GetFriendsRequest) (*friend.GetFriendsResponse, error) {
	l := logic.NewGetFriendsLogic(ctx, s.svcCtx)
	return l.GetFriends(in)
}

func (s *FriendServiceServer) GetPendingRequests(ctx context.Context, in *friend.GetFriendsRequest) (*friend.GetFriendsResponse, error) {
	l := logic.NewGetPendingRequestsLogic(ctx, s.svcCtx)
	return l.GetPendingRequests(in)
}

func (s *FriendServiceServer) DeleteFriend(ctx context.Context, in *friend.DeleteFriendRequest) (*friend.GeneralResponse, error) {
	l := logic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

func (s *FriendServiceServer) CreateFriendGroup(ctx context.Context, in *friend.CreateFriendGroupRequest) (*friend.CreateFriendGroupResponse, error) {
	l := logic.NewCreateFriendGroupLogic(ctx, s.svcCtx)
	return l.CreateFriendGroup(in)
}

func (s *FriendServiceServer) AddFriendToGroup(ctx context.Context, in *friend.AddFriendToGroupRequest) (*friend.GeneralResponse, error) {
	l := logic.NewAddFriendToGroupLogic(ctx, s.svcCtx)
	return l.AddFriendToGroup(in)
}

func (s *FriendServiceServer) GetFriendGroup(ctx context.Context, in *friend.GetFriendGroupRequest) (*friend.GetFriendGroupResponse, error) {
	l := logic.NewGetFriendGroupLogic(ctx, s.svcCtx)
	return l.GetFriendGroup(in)
}

func (s *FriendServiceServer) DeleteFriendFromGroup(ctx context.Context, in *friend.AddFriendToGroupRequest) (*friend.GeneralResponse, error) {
	l := logic.NewDeleteFriendFromGroupLogic(ctx, s.svcCtx)
	return l.DeleteFriendFromGroup(in)
}

func (s *FriendServiceServer) CheckIsFriend(ctx context.Context, in *friend.CheckIsFriendRequest) (*friend.CheckIsFriendResponse, error) {
	l := logic.NewCheckIsFriendLogic(ctx, s.svcCtx)
	return l.CheckIsFriend(in)
}
