// Code generated by goctl. DO NOT EDIT.
// Source: groupMessage.proto

package server

import (
	"context"

	"chatting/service/groupMessageService/internal/logic"
	"chatting/service/groupMessageService/internal/svc"
	"chatting/service/groupMessageService/pb/groupMessage"
)

type GroupMessageServiceServer struct {
	svcCtx *svc.ServiceContext
	groupMessage.UnimplementedGroupMessageServiceServer
}

func NewGroupMessageServiceServer(svcCtx *svc.ServiceContext) *GroupMessageServiceServer {
	return &GroupMessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupMessageServiceServer) SendGroupMessage(ctx context.Context, in *groupMessage.SendGroupMessageRequest) (*groupMessage.SendGroupMessageResponse, error) {
	l := logic.NewSendGroupMessageLogic(ctx, s.svcCtx)
	return l.SendGroupMessage(in)
}

func (s *GroupMessageServiceServer) GetGroupMessages(ctx context.Context, in *groupMessage.GetGroupMessagesRequest) (*groupMessage.GetGroupMessagesResponse, error) {
	l := logic.NewGetGroupMessagesLogic(ctx, s.svcCtx)
	return l.GetGroupMessages(in)
}

func (s *GroupMessageServiceServer) CreateGroup(ctx context.Context, in *groupMessage.CreateGroupRequest) (*groupMessage.CreateGroupResponse, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *GroupMessageServiceServer) AddGroupMember(ctx context.Context, in *groupMessage.AddGroupMemberRequest) (*groupMessage.AddGroupMemberResponse, error) {
	l := logic.NewAddGroupMemberLogic(ctx, s.svcCtx)
	return l.AddGroupMember(in)
}
