// Code generated by goctl. DO NOT EDIT.
// Source: friend.proto

package friendservice

import (
	"context"

	"chatting/service/friendService/pb/friend"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFriendRequest          = friend.AddFriendRequest
	AddFriendToGroupRequest   = friend.AddFriendToGroupRequest
	CheckIsFriendRequest      = friend.CheckIsFriendRequest
	CheckIsFriendResponse     = friend.CheckIsFriendResponse
	CreateFriendGroupRequest  = friend.CreateFriendGroupRequest
	CreateFriendGroupResponse = friend.CreateFriendGroupResponse
	DeleteFriendRequest       = friend.DeleteFriendRequest
	FriendGroupItem           = friend.FriendGroupItem
	FriendItem                = friend.FriendItem
	GeneralResponse           = friend.GeneralResponse
	GetFriendGroupRequest     = friend.GetFriendGroupRequest
	GetFriendGroupResponse    = friend.GetFriendGroupResponse
	GetFriendsRequest         = friend.GetFriendsRequest
	GetFriendsResponse        = friend.GetFriendsResponse

	FriendService interface {
		PendingRequest(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
		ConfirmRequest(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
		GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error)
		GetPendingRequests(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error)
		DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
		CreateFriendGroup(ctx context.Context, in *CreateFriendGroupRequest, opts ...grpc.CallOption) (*CreateFriendGroupResponse, error)
		AddFriendToGroup(ctx context.Context, in *AddFriendToGroupRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
		GetFriendGroup(ctx context.Context, in *GetFriendGroupRequest, opts ...grpc.CallOption) (*GetFriendGroupResponse, error)
		DeleteFriendFromGroup(ctx context.Context, in *AddFriendToGroupRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
		CheckIsFriend(ctx context.Context, in *CheckIsFriendRequest, opts ...grpc.CallOption) (*CheckIsFriendResponse, error)
	}

	defaultFriendService struct {
		cli zrpc.Client
	}
)

func NewFriendService(cli zrpc.Client) FriendService {
	return &defaultFriendService{
		cli: cli,
	}
}

func (m *defaultFriendService) PendingRequest(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.PendingRequest(ctx, in, opts...)
}

func (m *defaultFriendService) ConfirmRequest(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.ConfirmRequest(ctx, in, opts...)
}

func (m *defaultFriendService) GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.GetFriends(ctx, in, opts...)
}

func (m *defaultFriendService) GetPendingRequests(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.GetPendingRequests(ctx, in, opts...)
}

func (m *defaultFriendService) DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.DeleteFriend(ctx, in, opts...)
}

func (m *defaultFriendService) CreateFriendGroup(ctx context.Context, in *CreateFriendGroupRequest, opts ...grpc.CallOption) (*CreateFriendGroupResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.CreateFriendGroup(ctx, in, opts...)
}

func (m *defaultFriendService) AddFriendToGroup(ctx context.Context, in *AddFriendToGroupRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.AddFriendToGroup(ctx, in, opts...)
}

func (m *defaultFriendService) GetFriendGroup(ctx context.Context, in *GetFriendGroupRequest, opts ...grpc.CallOption) (*GetFriendGroupResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.GetFriendGroup(ctx, in, opts...)
}

func (m *defaultFriendService) DeleteFriendFromGroup(ctx context.Context, in *AddFriendToGroupRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.DeleteFriendFromGroup(ctx, in, opts...)
}

func (m *defaultFriendService) CheckIsFriend(ctx context.Context, in *CheckIsFriendRequest, opts ...grpc.CallOption) (*CheckIsFriendResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.CheckIsFriend(ctx, in, opts...)
}
