// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userservice

import (
	"context"

	"chatting/service/userService/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckUserExistRequest     = user.CheckUserExistRequest
	CheckUserExistResponse    = user.CheckUserExistResponse
	GetUserNameByIdRequest    = user.GetUserNameByIdRequest
	GetUserNameByIdResponse   = user.GetUserNameByIdResponse
	GetUserProfileRequest     = user.GetUserProfileRequest
	GetUserProfileResponse    = user.GetUserProfileResponse
	LoginRequest              = user.LoginRequest
	LoginResponse             = user.LoginResponse
	LogoutRequest             = user.LogoutRequest
	LogoutResponse            = user.LogoutResponse
	RegisterRequest           = user.RegisterRequest
	RegisterResponse          = user.RegisterResponse
	UpdateUserProfileRequest  = user.UpdateUserProfileRequest
	UpdateUserProfileResponse = user.UpdateUserProfileResponse
	ValidateRequest           = user.ValidateRequest
	ValidateResponse          = user.ValidateResponse

	UserService interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
		ValidateJWT(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
		UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UpdateUserProfileResponse, error)
		GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
		CheckUserExist(ctx context.Context, in *CheckUserExistRequest, opts ...grpc.CallOption) (*CheckUserExistResponse, error)
		GetUserNameById(ctx context.Context, in *GetUserNameByIdRequest, opts ...grpc.CallOption) (*GetUserNameByIdResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserService) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultUserService) ValidateJWT(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.ValidateJWT(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UpdateUserProfileResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserProfile(ctx, in, opts...)
}

func (m *defaultUserService) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserProfile(ctx, in, opts...)
}

func (m *defaultUserService) CheckUserExist(ctx context.Context, in *CheckUserExistRequest, opts ...grpc.CallOption) (*CheckUserExistResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.CheckUserExist(ctx, in, opts...)
}

func (m *defaultUserService) GetUserNameById(ctx context.Context, in *GetUserNameByIdRequest, opts ...grpc.CallOption) (*GetUserNameByIdResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserNameById(ctx, in, opts...)
}
